USE ZIMPLIFY;

CREATE VIEW ZDV_SYOB_GET ON SELECT * FROM ZIMPLIFY_OBJECTS;
CREATE VIEW ZDV_DCOB_GET ON SELECT * FROM ZIMPLIFY_DOCUMENTS;
CREATE VIEW ZDV_EVOB_GET ON SELECT * FROM ZIMPLIFY_EVENTS;
CREATE VIEW ZDV_MGOB_GET ON SELECT * FROM ZIMPLIFY_MESSAGES: